---
title: "Microbial Innovations"
author: "Mario E. Muscarella, James P. O'Dwyer"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
  - \usepackage{graphics}
output: 
  pdf_document:
  fig_caption: true
---

## Initial Setup
```{r}
# Clear Environment and Set Working Directory
rm(list=ls())
setwd("~/GitHub/microbial-innovations/analyses")

# Add Basic Functions
se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
ci <- function(x, ...){1.96 * sd(x,na.rm = TRUE)}

# Load Packages
require("ape"); require("png"); require("grid")
require("ggtree")

# Load Source Functions
source("../bin/MothurTools.R")

# Save Default Plot Settings
opar <- par(no.readonly = TRUE)  # Saves plot defaults
```

## Import Tree Files
```{r}
LTP <- read.tree("../data/LTPs123.tree")
NTL <- read.tree("../data/NTL.tree")
RDP <- read.tree("../data/RDP.tree")

plot(LTP, show.tip.label = F)

```

## Import Taxonomy Information
```{r}
LTP.tax <- read.tax("../data/LTPs123_unique.pds.wang.taxonomy", format = "rdp", col.tax = 2)
NTL.tax <- read.tax("../data/nmicrobiol201648_s7.pds.wang.taxonomy", format = "rdp", col.tax = 2)
RDP.tax <- read.tax("../data/rdp_download_9752seqs.pds.wang.taxonomy", format = "rdp", col.tax = 2)
```


# Edge Length Distribution
```{r}
LTP.edges <- LTP$edge.length
NTL.edges <- NTL$edge.length
RDP.edges <- RDP$edge.length

png(filename="../figures/BranchLengths.png",
    width = 800, height = 1600, res = 96*2)
layout(matrix(1:3, 3, 1))
par(mar = c(5, 6, 3, 1) + 0.1, oma = c(1,1,1,1))

hist(log10(LTP.edges), main = "Silva: Living Tree Project",
     axes = F, xlab = "", ylab = "", xlim = c(-4, 1))

axis(1, at = c(-4, -3, -2, -1, 0, 1), 
     labels = expression(10^-4, 10^-3, 10^-2, 10^-1, 1, 10^1),  
     las = 1, lwd = 1.5)
axis(2, labels = T, las = 1, lwd = 1.5)

mtext("Edge Length", side = 1, cex = 1, line = 2.5)
mtext("Frequency", side = 2, cex = 1, line = 4)

hist(log10(NTL.edges), main = "Hug et al. 2016: New Tree of Life",
     axes = F, xlab = "", ylab = "", xlim = c(-4, 1))

axis(1, at = c(-4, -3, -2, -1, 0, 1), 
     labels = expression(10^-4, 10^-3, 10^-2, 10^-1, 1, 10^1),  
     las = 1, lwd = 1.5)
axis(2, labels = T, las = 1, lwd = 1.5)

mtext("Edge Length", side = 1, cex = 1, line = 2.5)
mtext("Frequency", side = 2, cex = 1, line = 4)

hist(log10(RDP.edges), main = "Ribosomal Datebase Project",
     axes = F, xlab = "", ylab = "", xlim = c(-4, 1))

axis(1, at = c(-4, -3, -2, -1, 0, 1), 
     labels = expression(10^-4, 10^-3, 10^-2, 10^-1, 1, 10^1),  
     las = 1, lwd = 1.5)
axis(2, labels = T, las = 1, lwd = 1.5)

mtext("Edge Length", side = 1, cex = 1, line = 2.5)
mtext("Frequency", side = 2, cex = 1, line = 4)



# Close Plot Device
dev.off()
graphics.off()
#```
## Show Plot
#```{r}
img <- readPNG("../figures/BranchLengths.png")
grid.raster(img)
```

## Edge Length vs Support
```{r}
node.tab <- data.frame(matrix(NA, LTP$Nnode, 5))
colnames(node.tab) <- c("node", "support", "edge_up", "edge_down1", "edge_down2")
node.tab$node <- as.numeric(c(1:LTP$Nnode))
node.tab$support <- LTP$node.label
node.tab[1,3] <- NA
for (i in 2:LTP$Nnode){
  edge.up <- which(LTP$edge[,2] == length(LTP$tip.label) + i)
  node.tab[i,3] <- LTP$edge.length[edge.up]
  edge.down <- which(LTP$edge[,1] == length(LTP$tip.label) + i)
  node.tab[i,4] <- LTP$edge.length[edge.down[1]]
  node.tab[i,5] <- LTP$edge.length[edge.down[2]]
}
node.tab$edge_down_min <- apply(cbind(node.tab$edge_down1, node.tab$edge_down2), 1, min)

scatterhist = function(x, y, xlab="", ylab=""){
  zones=matrix(c(2,0,1,3), ncol=2, byrow=TRUE)
  par(oma = c(1,1,1,1))
  layout(zones, widths=c(4/5,1/5), heights=c(1/5,4/5))
  xhist = hist(x, plot=FALSE)
  yhist = hist(y, plot=FALSE)
  top = max(c(xhist$counts, yhist$counts))
  par(mar=c(5,5,1,1))
  plot(x,y, las = 1, xlab = "", ylab = "")
  mtext(xlab, side=1, line=3, outer=F, cex = 1.25)
  mtext(ylab, side=2, line=3, outer=F, cex = 1.25)
  par(mar=c(0,5,1,1))
  barplot(xhist$counts, axes=FALSE, space=0)
  par(mar=c(5,0,1,1))
  barplot(yhist$counts, axes=FALSE, space=0, horiz=TRUE)
}


# Upstream
scatterhist(x = log10(node.tab$edge_up), y = as.numeric(node.tab$support),
            xlab = "Upstream Edge Length", ylab = "Node Support")

# Downstream
scatterhist(log10(node.tab$edge_down_min), as.numeric(node.tab$support),
            xlab = "Downstream Edge Length", ylab = "Node Support")

mean(as.numeric(node.tab$support), na.rm = T)
mean(as.numeric(node.tab$support[log10(node.tab$edge_up) < -1.75]), na.rm = T)
mean(as.numeric(node.tab$support[log10(node.tab$edge_up) > 0.75]), na.rm = T)
mean(as.numeric(node.tab$support[log10(node.tab$edge_up) < -2.25]), na.rm = T)

```

## Exploratory Tree with Domain Grouping
```{r, results = "hide"}
png(filename="../figures/LTP_explore.png",
    width = 1600, height = 1600, res = 96*2)


LTP.2 <- LTP
groupInfo <- split(LTP.2$tip.label, LTP.tax2$Domain)
livingTree <- groupOTU(LTP.2, groupInfo, group_name = "Domain")
levels(attributes(livingTree)$Domain) <- names(groupInfo)
ggtree(livingTree, aes(color = Domain), layout="rectangular") + 
  geom_text2(aes(subset=!isTip, label = node), hjust=-0.1, vjust = -0.5, size = 2) + 
  #geom_tiplab(size=1) + 
  theme(legend.position="top", legend.key = element_rect(colour = NA))


# Close Plot Device
dev.off()
graphics.off()
#```
## Show Plot
#```{r}
img <- readPNG("../figures/LTP_explore.png")
grid.raster(img)
```




## Example Trees
```{r}

nwk <- system.file("extdata", "sample.nwk", package="ggtree")
tree <- read.tree(nwk)
ggtree(tree) + geom_text2(aes(subset=!isTip, label=node), hjust=-.3) + geom_tiplab()
ggtree(tree, layout="fan", open.angle=180) + ggtitle("(Phylogram) circular layout")
ggtree(tree, layout="unrooted") + ggtitle("(Phylogram) circular layout")



MRCA(tree, tip = c("A", "E"))
p <- ggtree(tree)
MRCA(p, tip=c('A', 'E'))

viewClade(p+geom_tiplab(), node = 21)

tree <- groupClade(tree, node = 21)
ggtree(tree, aes(color=group, linetype=group))

tree <- groupClade(tree, node=c(21, 17))
ggtree(tree, aes(color=group, linetype=group)) + geom_tiplab(aes(subset=(group==2)))

tree <- groupClade(tree, node = c(21,17))
ggtree(tree, aes(color=group, linetype = group)) + geom_tiplab(aes(subset=(group==2)))

tree <- groupOTU(tree, focus=c("D", "E", "F", "G"))

ggtree(tree, aes(color=group)) + geom_tiplab()

library("ape")
data(chiroptera)
groupInfo <- split(chiroptera$tip.label, gsub("_\\w+", "", chiroptera$tip.label))
chiroptera <- groupOTU(chiroptera, groupInfo)
ggtree(chiroptera, aes(color=group), layout='circular') + geom_tiplab(size=1, aes(angle=angle))


LTP$tip.label[1:5]
LTP.tax[1:5,1:5]

sum(LTP$tip.label %in% LTP.tax$OTU) == length(LTP$tip.label %in% LTP.tax$OTU)

LTP$tip.label == LTP.tax$OTU
LTP.tax2 <- LTP.tax[match(LTP$tip.label, LTP.tax$OTU), ]

all(LTP$tip.label == LTP.tax2$OTU)

LTP.2 <- LTP
groupInfo <- split(LTP.2$tip.label, LTP.tax2$Domain)
livingTree <- groupOTU(LTP.2, groupInfo, group_name = "Domain")
levels(attributes(livingTree)$Domain) <- names(groupInfo)
ggtree(livingTree, aes(color = Domain), layout="rectangular") + 
  geom_text2(aes(subset=!isTip, label = node), hjust=-0.1, vjust = -0.5, size = 2) + 
  #geom_tiplab(size=1) + 
  theme(legend.position="right")


library("colorspace")
ggtree(livingTree, aes(color=group, linetype=group)) + geom_tiplab() + 
  geom_text2(aes(subset=!isTip, label = node), hjust=-0.3) + 
  scale_color_manual(values=c("black", rainbow_hcl(10))) + theme(legend.position="right")


groupInfo <- split(chiroptera$tip.label, gsub("_\\w+", "", chiroptera$tip.label))
chiroptera <- groupOTU(chiroptera, groupInfo)
ggtree(chiroptera, aes(color=group), layout='circular') + geom_tiplab(size=1, aes(angle=angle))
```
