---
title: "Microbial Innovations: Simulations"
author: "Mario E Muscarella"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
  - \usepackage{graphics}
output: 
  pdf_document: 
    fig_caption: yes
---

# Initial Setup
```{r setup, include=FALSE}
# Knitr Options
knitr::opts_chunk$set(echo = TRUE)

# Clear Environment and Set Working Directory
rm(list=ls())
setwd("~/GitHub/microbial-innovations/analyses")

# Load Packages
library("phytools")
library("ape")
library("mnormt")
library("MASS")
library("expm")
library("diagram")
library("adephylo")
require("grid")
require("png")
library("geiger")
```

# Trait Evolution Simulations
## Basic Trait Evolution Simulation
```{r}
# Import Simulation Results (Range of A Or B)
simA <- read.table("../simulations/output/TraitEvolution_A.txt", header = 1)
simB <- read.table("../simulations/output/TraitEvolution_B.txt", header = 1)

# Plot Simulation Results
png(filename="../figures/TraitEvolution_A.png",
    width = 1600, height = 800, res = 96*2)

layout(matrix(1:2, 1, 2))

par(mar = c(4,1,1,1) + 0.5, oma = c(1, 4, 0.5, 0.5))

plot(simA$test.a, simA$sim.mean, las = 1, pch = 16,
     xlim = c(0.4, 1.0), ylim = c(5, 60),
     xlab = "Alpha Parameter", ylab = "")
arrows(simA$test.a, y0 = simA$sim.mean - simA$sim.sem,
       y1 = simA$sim.mean + simA$sim.sem, length = 0)
legend("topleft", legend = expression(paste(beta, " = 0.90")), 
       bty = "n", xjust = 0, lty = 0, adj = c(0.3, 0.5))
mtext(side = 2, "Mean 1st Occurrence (time)", cex = 1, line = 3)

plot(simB$test.b, simB$sim.mean, las = 1, pch = 16,
     xlim = c(0.4, 1.0), ylim = c(5, 60),
     xlab = "Beta Parameter", ylab = "")
arrows(simB$test.b, y0 = simB$sim.mean - simB$sim.sem,
       y1 = simB$sim.mean + simB$sim.sem, length = 0)
legend("topright", legend = expression(paste(alpha, " = 0.90")), 
       bty = "n", xjust = 0, lty = 0)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/TraitEvolution_A.png")
grid.raster(img)
```

```{r}
# Load Simulation A/B (range A and B)
simAB <- read.table("../simulations/output/TraitEvolution_AB.txt", header = 1)

simAB[simAB == Inf] <- NA

# Plot 
png(filename="../figures/TraitEvolution_B.png",
    width = 800, height = 800, res = 96*2)

par(mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))

l <- length(unique(simAB[,1]))
w <- length(unique(simAB[,2]))

simAB[1, 1] == simAB[1, 2]
simAB[1, 1] == simAB[1 + l, 2]
simAB[1, 1] == simAB[2, 1]
simAB[1, 2] == simAB[2, 2]
# Col 2 (B) stays constant until all values in Col 1 (A) are used

z <- matrix(c(NA, simAB[, 3]), nrow = l, ncol = w, byrow = F)

nrz <- nrow(z)
ncz <- ncol(z)
# Create a function interpolating colors in the range of specified colors
jet.colors <- colorRampPalette( c("blue", "green") )
# Generate the desired number of colors from this palette
nbcol <- 100
color <- jet.colors(nbcol)
# Compute the z-value at the facet centres
zfacet <- z[-1, -1] + z[-1, -ncz] + z[-nrz, -1] + z[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zfacet, nbcol)
par(mar = c(1, 1, 1, 1) + 0.5)
persp(z = z, phi = 15, theta = 215,
      zlim = c(0, 75), ticktype = "simple", nticks = 4,
      xlab = "Alpha", ylab = "Beta", zlab = "Mean 1st Occurrence (time)",
      col = color[facetcol], scale = TRUE)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/TraitEvolution_B.png")
grid.raster(img)
```

### Level Plot Version
```{r}
# Plot 
png(filename="../figures/TraitEvolution_B_level.png",
    width = 900, height = 800, res = 96*2)

par(mar = c(2, 2, 4, 2), oma = c(0, 0, 1, 0))

levelplot(simAB[, 3] ~ simAB[, 1] + simAB[, 2], pretty = T,
          xlab = "Alpha", ylab = "Beta", main = "Mean 1st Occurrence (time)", 
          col.regions = color,
          outer = T, allow.multiple = T)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/TraitEvolution_B_level.png")
grid.raster(img)
```

## Flat or Defined Prior for Root Probabilities
```{r}
# Import Simulation Results
sim.flat <- 
sim.prior <- 

# Plot
png(filename="../figures/TraitEvolution_C.png",
    width = 1800, height = 800, res = 96*2)
layout(matrix(1:2, 1, 2))

# No Prior (flat 0.5, 0.5)
x <- test.a
y <- test.b
z <- matrix(sim.lik[, 3], nrow = length(test.a), ncol = length(test.b))
nrz <- nrow(z)
ncz <- ncol(z)
# Create a function interpolating colors in the range of specified colors
jet.colors <- colorRampPalette( c("blue", "green") )
# Generate the desired number of colors from this palette
nbcol <- 100
color <- jet.colors(nbcol)
# Compute the z-value at the facet centres
zfacet <- z[-1, -1] + z[-1, -ncz] + z[-nrz, -1] + z[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zfacet, nbcol)
par(mar = c(2, 2, 2, 2) + 0.5)
persp(z = z, phi = 15, theta = 30,
      zlim = c(0.25, 0.8), ticktype = "simple", nticks = 4,
      xlab = "Alpha", ylab = "Beta", zlab = "Likelihood of State",
      main = "No Prior", 
      col = color[facetcol], scale = FALSE)


# Defined Prior (0.99, 0.01)
x <- test.a
y <- test.b
z <- matrix(sim.lik[, 3], nrow = length(test.a), ncol = length(test.b))
nrz <- nrow(z)
ncz <- ncol(z)
# Create a function interpolating colors in the range of specified colors
jet.colors <- colorRampPalette( c("blue", "green") )
# Generate the desired number of colors from this palette
nbcol <- 100
color <- jet.colors(nbcol)
# Compute the z-value at the facet centres
zfacet <- z[-1, -1] + z[-1, -ncz] + z[-nrz, -1] + z[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zfacet, nbcol)
par(mar = c(2, 2, 2, 2) + 0.5)
persp(z = z, phi = 15, theta = 30,
      zlim = c(0.25, 1), ticktype = "simple", nticks = 4,
      xlab = "Alpha", ylab = "Beta", zlab = "Likelihood of State",
      main = "With Root Prior",
      col = color[facetcol], scale = FALSE)

# Close Plot Device
dev.off()
graphics.off()


```


# ConsenTrait Simulations
```{r}
# Import Simulation Results
CT.sim <- read.delim("../simulations/output/ConsenTraitSimulation.txt", 
                     header = T)

# Plot
png(filename="../figures/ConsenTraitSimulation.png",
    width = 1600, height = 800, res = 96*2)
layout(matrix(1:2, 1, 2))
par(mar = c(4, 1, 3, 1) + 0.5, oma = c(0, 3, 0, 0))
plot(CT.sim$first.obs.mean, CT.sim$first.pred.mean,
     xlab = "", ylab = "", las = 1,
     xlim = c(0, 80), ylim = c(0,100),
     col=rgb(0, 0, 1, 0.5), pch=16)
abline(0, 1, lwd = 1, lty = 2)
mtext(side = 1, text = "Observed", line = 2.5, cex = 1.25)
mtext(side = 2, text = "Predicted", line = 2.5, outer = F, cex = 1.25)
mtext(side = 3, text = "First Occurence (Time)", line = 1, cex = 1.25)
plot(CT.sim$nevol.obs.mean, CT.sim$nevol.pred.mean,
     xlab = "", ylab = "", las = 1,
     xlim = c(0, 55), ylim = c(0, 25),
     col=rgb(0, 0, 1, 0.5), pch=16)
abline(0, 1, lwd = 1, lty = 2)
mtext(side = 1, text = "Observed", line = 2.5, cex = 1.25)
#mtext(side = 2, text = "Predicted", line = 2.5, outer = F, cex = 1.25)
mtext(side = 3, text = "Number of Occurences", line = 1, cex = 1.25)


# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/ConsenTraitSimulation.png")
grid.raster(img)

```

# Ancestral State Reconstruction Simulations
```{r}
# Import Simulation Results
ASR.sim <- read.delim("../simulations/output/asr_simulation.txt", 
                     header = T)
source("../bin/TreeSimulationFxns.R")


ASR.sim$pred.Alpha <- NA; ASR.sim$pred.Beta <- NA

for(i in 1:dim(ASR.sim)[1]){
  temp <- unlist(xy_to_ab(x = -ASR.sim$Mean_X[i], y = -ASR.sim$Mean_Y[i]))
  ASR.sim[i, ]$pred.Alpha <- (1 - temp[1])
  ASR.sim[i, ]$pred.Beta <- (1 - temp[2])
}

# Plot
png(filename="../figures/ASRSimulation_MC.png",
    width = 1600, height = 800, res = 96*2)
layout(matrix(1:2, 1, 2))
par(mar = c(4, 1, 3, 1) + 0.5, oma = c(0, 3, 0, 0))

plot(jitter(ASR.sim$Alpha), ASR.sim$pred.Alpha,
     xlim = c(0.5, 1), ylim = c(0, 1), las = 1,
     xlab = "True Value", ylab = "",
     cex = c(2 - 1.5*ASR.sim$Beta),
     col=rgb(0, 0, 1, 0.5), pch=16)
legend("topleft", "Size rev. scaled by beta", bty = "n")
mtext(side = 3, text = "Prediction: Alpha Parameter", line = 1, cex = 1.25)
abline(0, 1, lty = 2)
mod1 <- lm(ASR.sim$pred.Alpha ~ ASR.sim$Alpha * ASR.sim$Beta)
mod1

mtext(side = 2, text = "Predicted Value", line = 3)

plot(jitter(ASR.sim$Beta), ASR.sim$pred.Beta,
     xlim = c(0.5, 1), ylim = c(0, 1), las = 1,
     xlab = "True Value", 
     cex = c(2 - 1.5*ASR.sim$Alpha),
     col=rgb(0, 0, 1, 0.5), pch=16)
mtext(side = 3, text = "Prediction: Beta Parameter", line = 1, cex = 1.25)

legend("topleft", "Size rev. scaled by alpha", bty = "n")
abline(0, 1, lty = 2)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/ASRSimulation_MC.png")
grid.raster(img)
```

```{r}
# Plot
png(filename="../figures/ASRTraitSimulation.png",
    width = 1600, height = 800, res = 96*2)
layout(matrix(1:2, 1, 2))
par(mar = c(4, 1, 3, 1) + 0.5, oma = c(0, 3, 0, 0))
plot(CT.sim$first.obs.mean, CT.sim$first.pred.mean,
     xlab = "", ylab = "", las = 1,
     xlim = c(0, 80), ylim = c(0,100),
     col=rgb(0, 0, 1, 0.5), pch=16)
abline(0, 1, lwd = 1, lty = 2)
mtext(side = 1, text = "Observed", line = 2.5, cex = 1.25)
mtext(side = 2, text = "Predicted", line = 2.5, outer = F, cex = 1.25)
mtext(side = 3, text = "First Occurence (Time)", line = 1, cex = 1.25)
plot(CT.sim$nevol.obs.mean, CT.sim$nevol.pred.mean,
     xlab = "", ylab = "", las = 1,
     xlim = c(0, 55), ylim = c(0, 25),
     col=rgb(0, 0, 1, 0.5), pch=16)
abline(0, 1, lwd = 1, lty = 2)
mtext(side = 1, text = "Observed", line = 2.5, cex = 1.25)
#mtext(side = 2, text = "Predicted", line = 2.5, outer = F, cex = 1.25)
mtext(side = 3, text = "Number of Occurences", line = 1, cex = 1.25)


# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../figures/ASRTraitSimulation.png")
grid.raster(img)

```






```{r}

plot(ASR.sim$Alpha, ASR.sim$LogL,
     xlim = c(0.4, 1), ylim = c(-80, 0), las = 1,
     xlab = "Simulation Alpha Parameter", ylab = "Log Likelihood",
          cex = c(2 - 1.5*ASR.sim$Beta),
     col=rgb(0, 0, 1, 0.5), pch=16)

plot(ASR.sim$Beta, ASR.sim$LogL,
     xlim = c(0.4, 1), ylim = c(-80, 0), las = 1,
     xlab = "Simulation Beta Parameter", ylab = "Log Likelihood",
          cex = c(2 - 1.5*ASR.sim$Alpha),
     col=rgb(0, 0, 1, 0.5), pch=16)
```

```{r}

# Surface Plot
x <- sort(unique(ASR.sim$Alpha))
y <- sort(unique(ASR.sim$Beta))
z <- matrix(NA, nrow = length(x), ncol = length(y))

for(i in 1:length(x)){
  for(j in 1:length(y)){
    z[i, j] <- ASR.sim[ASR.sim$Alpha == x[i] & ASR.sim$Beta == y[j], ]$LogL_sem
  }
}
nrz <- nrow(z); ncz <- ncol(z)

# Create a function interpolating colors in the range of specified colors
jet.colors <- colorRampPalette( c("blue", "green") )
# Generate the desired number of colors from this palette
nbcol <- 100
color <- jet.colors(nbcol)
# Compute the z-value at the facet centres
zfacet <- z[-1, -1] + z[-1, -ncz] + z[-nrz, -1] + z[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zfacet, nbcol)
layout(matrix(1))
par(mar = c(2, 2, 2, 2) + 0.5)
persp(z = z, phi = 15, theta = 300,
      zlim = c(0, 1), ticktype = "simple", nticks = 4,
      xlab = "Alpha Parameter", ylab = "Beta Parameter", 
      zlab = "Neg Log Likelihood (SEM)",
      main = "Ancestral State Reconstruction", 
      col = color[facetcol], scale = TRUE)



#hist(ASR.sim$LogL)



```





